<?php
define('POS_APP', true);
require_once __DIR__ . '/config/config.php';
SessionManager::start();
Security::applySecurityHeaders();
$csrfToken = Security::generateCsrfToken();
$pageTitle = 'Reset Password';
$token = trim($_GET['token'] ?? '');
?>
<!DOCTYPE html><html lang="en"><head><?php require __DIR__ . '/includes/header.php'; ?></head><body class="pos-login-body"><main class="pos-reset-page"><section class="pos-reset-card"><div class="pos-brand mb-4"><span class="pos-brand-mark">POS</span><span class="pos-brand-rest">STORE</span></div><h1 class="pos-login-title">Create a new password</h1><p class="pos-login-subtitle">Choose a password with at least 8 characters, including a letter and number.</p><div id="resetAlert" class="alert d-none" role="alert"></div><?php if (!preg_match('/^[a-f0-9]{64}$/', $token)): ?><div class="alert alert-danger">This password reset link is invalid or has expired.</div><a class="pos-link small" href="<?= APP_URL ?>/login.php">Back to sign in</a><?php else: ?><form id="resetPasswordForm"><input type="hidden" id="resetToken" value="<?= Security::escape($token) ?>"><div class="mb-3"><label class="form-label" for="newResetPassword">New password</label><input type="password" class="form-control" id="newResetPassword" autocomplete="new-password" required minlength="8"></div><div class="mb-4"><label class="form-label" for="confirmResetPassword">Confirm new password</label><input type="password" class="form-control" id="confirmResetPassword" autocomplete="new-password" required minlength="8"></div><button class="btn pos-btn-primary w-100" id="resetPasswordBtn" type="submit">Reset password</button></form><?php endif; ?><p class="text-center mt-4 mb-0"><a class="pos-link small" href="<?= APP_URL ?>/login.php">Back to sign in</a></p></section></main><script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script>window.APP_URL=<?= json_encode(APP_URL) ?>;</script><script>$(function(){ $('#resetPasswordForm').on('submit',function(e){e.preventDefault();const password=$('#newResetPassword').val(),confirm=$('#confirmResetPassword').val(),$a=$('#resetAlert'),$b=$('#resetPasswordBtn');$a.addClass('d-none');if(password!==confirm){$a.removeClass('d-none alert-success').addClass('alert-danger').text('Passwords do not match.');return;}$b.prop('disabled',true).text('Resetting...');$.post(window.APP_URL+'/app/controllers/PasswordResetController.php',{action:'reset',token:$('#resetToken').val(),password:password,confirm_password:confirm,csrf_token:<?= json_encode($csrfToken) ?>}).done(function(r){$a.removeClass('d-none alert-danger').addClass('alert-success').text(r.message);$('#resetPasswordForm').hide();}).fail(function(x){$a.removeClass('d-none alert-success').addClass('alert-danger').text((x.responseJSON&&x.responseJSON.message)||'Could not reset the password.');}).always(function(){$b.prop('disabled',false).text('Reset password');});});});</script></body></html>
